### ISSUE TITLE
Game objective visualization

### ISSUE THREAD

**Issue by david-daal** [Snowblaze/Squarepop#2]
It's not possible to understand what is game objective now.
There are just two numbers drawn. 
Please add color for every objective.  Like in Match3Test project screenshot.
![screen shot 2018-01-08 at 1 06 52 pm](https://user-images.githubusercontent.com/2318278/34664356-e3176f5c-f474-11e7-9a19-f47bedb1f400.png)

**Comment by Snowblaze** [comment]
Fixed.
